const genreTable = [
    "Finance",
    "Orienté local",
    "Business",
    "Technologie",
    "Enfants et Famille",
    "Société et culture",
    "Fiction",
    "Forme et Santé",
    "Musique",
    "Actualités",
    "Comédie",
    "Arts",
    "Sports",
    "Loisirs",
    "Télé et Films",
    "Histoire",
    "Sciences",
    "Education",
    "True Crime",
    "Religion et spiritualité",
    "Gouvernement",
];

export default { genreTable}